HUE_PARAMS = {
    'ilowH' : 65,
    'ihighH' : 156,
    'ilowS' : 80,
    'ihighS' : 255,
    'ilowV' : 0,
    'ihighV' : 189,
}
MARGIN_DICT = {
    'small_area_margin': 50,
    'large_area_margin': -10,
    'area_threshold_min': 500,
    'area_threshold_max': 5000,
}
SIZE_AREA_DICT = {
    'thresh1': 3000,
    'thresh2': 5000 
}
MIN_CCA_AREA = 20
MAX_CCA_AREA = 30000

RESIZE_IMAGE_LENGTH = 120

ENDPOINT = "PASTE_YOUR_CUSTOM_VISION_TRAINING_ENDPOINT_HERE"
TRAINING_KEY = "PASTE_YOUR_CUSTOM_VISION_TRAINING_SUBSCRIPTION_KEY_HERE"
PREDICTION_KEY = "PASTE_YOUR_CUSTOM_VISION_PREDICTION_SUBSCRIPTION_KEY_HERE"
PREDICTION_RESOURCE_ID = "PASTE_YOUR_CUSTOM_VISION_PREDICTION_RESOURCE_ID_HERE"